name: Build and Simulate (STM32F401)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ARM toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi cmake ninja-build

      - name: Build firmware only
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
          cmake --build build --target firmware.elf
          arm-none-eabi-objcopy -O binary build/firmware.elf build/firmware.bin

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/firmware.elf

  simulate:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download firmware
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: build

      - name: Install QEMU (ARM version)
        run: |
          sudo apt update
          sudo apt install -y qemu-system-arm

      - name: Verify QEMU installation
        run: qemu-system-arm --version

      - name: Run firmware in QEMU
        run: |
          qemu-system-arm -M stm32-p103 -kernel build/firmware.elf -nographic -serial stdio -semihosting
