name: Build Firmware (STM32F401)

on:
  push:
    branches:
      - main  # فقط در صورت push به برنچ main اجرا می‌شود
  pull_request:
    branches:
      - main  # فقط برای pull request‌هایی که هدف‌شون برنچ main است

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi cmake ninja-build

      - name: Build firmware
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/toolchain-arm-gcc.cmake
          cmake --build build --target firmware.elf
          arm-none-eabi-objcopy -O binary build/firmware.elf build/firmware.bin

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/firmware.elf
            build/firmware.bin

  simulate:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download firmware
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: build

      - name: Install QEMU with STM32F4 support
        env:
          QEMU_VERSION: 7.2.0-1
        run: |
          ARCHIVE="xpack-qemu-arm-${QEMU_VERSION}-linux-x64.tar.gz"
          wget -q "https://github.com/xpack-dev-tools/qemu-arm-xpack/releases/download/v${QEMU_VERSION}/${ARCHIVE}"
          tar -xzf "${ARCHIVE}"
          echo "${PWD}/xpack-qemu-arm-${QEMU_VERSION}/bin" >> "$GITHUB_PATH"

      - name: Verify QEMU installation
        run: qemu-system-gnuarmeclipse --version

      - name: Run firmware in QEMU
        run: |
          timeout 5s qemu-system-gnuarmeclipse \
            --board STM32F4-Discovery \
            --image build/firmware.elf \
            --semihosting-config enable=on,target=native \
            --nographic \
            --monitor null \
            --serial stdio || true

