name: Build Firmware (STM32F401)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ARM toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi cmake ninja-build

      - name: Configure and Build firmware
        run: |
          cmake -B build -G Ninja
          cmake --build build

      - name: Convert ELF to BIN
        run: |
          arm-none-eabi-objcopy -O binary build/firmware.elf build/firmware.bin

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/firmware.elf
