name: Embedded DevOps CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Install clang-format
      - name: Install clang-format
        run: sudo apt-get install clang-format

      # Format code
      - name: Run clang-format
        run: |
          find . -iname "*.c" -o -iname "*.h" | xargs clang-format -i


      - name: Clone Unity framework
        run: |
          mkdir -p third_party
          if [ ! -d "third_party/Unity" ]; then
            git clone https://github.com/ThrowTheSwitch/Unity.git third_party/Unity
          fi

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build gcc

      - name: Configure project
        run: cmake -S . -B build -G "Ninja"

      - name: Build all targets
        run: cmake --build build -j

      - name: Run tests
        run: cd build && ctest --output-on-failure
      # Install lcov
      - name: Install lcov
        run: sudo apt-get install lcov

      # Generate coverage report
      - name: Generate coverage report
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/test/*' --output-file coverage.info
          lcov --list coverage.info
