name: Build Firmware (STM32F401)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ARM GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Configure
        run: cmake -S . -B build \
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/toolchain-arm-gcc.cmake

      - name: Build firmware
        run: cmake --build build --target firmware.elf --parallel

      - name: Convert to .bin
        run: arm-none-eabi-objcopy -O binary build/firmware.elf build/firmware.bin

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/firmware.elf
            build/firmware.bin

  simulate:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install QEMU (ARM)
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-arm

      - uses: actions/download-artifact@v4
        with:
          name: firmware
          path: build

      - name: Run firmware in QEMU
        run: qemu-system-arm -M stm32f4discovery -kernel build/firmware.elf -nographic -serial stdio -semihosting
